Sinclebear/makehabit_BE

- middlewares/auth-middleware.js
- routes/proofshot.js
🐛 bugfix: Bearer null 비회원 상태일때 로직 정상 동작하도록 변경
> Proofshot_auth middleware 수정

- routes/proofshot.js
- routes/user.js
user.js - feature : token 전송 시 nickname도 보내도록 설정
proofShot.js - feature: 인증페이지 조회 response 수정. 필요한 내용만 전송
> proofshot to dev merge

- package-lock.json
- package.json
1. 테스트 코드 관련 : jest, supertest (dev dependency)
2. 소셜로그인(카카오) 관련 : passport, passport-kakao
3. 서버 로그 남기기 관련 : winston, winston-daily-rotate-file, winston-telegram, morgan
> 🚧 update: 2주차 도전해볼 라이브러리 설치 (테스트 코드, 소셜로그인, 서버 로깅)

- .eslintrc
- .gitignore
- .prettierrc
- app.js
- middlewares/auth-middleware.js
- models/challenge.js
- models/index.js
- models/proofShot.js
- models/user.js
- modules/calcProperty.js
- modules/multer.js
- modules/swagger.js
- package-lock.json
- package.json
- routes/challenge.js
- routes/mypage.js
- routes/proofshot.js
- routes/upload.js
- routes/user.js
- swagger/user.js
> Dev -> Main 병합

- routes/mypage.js
feat: 캐릭터 정보 조회, 좋아요 모아보기 기능 추가
> feat: 캐릭터 정보 조회, 좋아요 모아보기 기능 추가

- routes/mypage.js
🐛 api/challenge 에서 content 보내도록 수정.
> 🐛 api/challenge 에서 content 보내도록 수정.

- routes/mypage.js
> 🤡 createtest 수행

- controller/auth.js
- passport/index.js
> 🐛 feat: kakao 로그인 동작되도록 변경

- models/index.js
변경내용 : 데이터베이스 접속 시, 암호에 특수문자가 들어갈 경우 url encoding이 필요 
`useNewUrlParser: true` 옵션을 추가하여, url encode된 특수문자를 다시 원하는 특수문자 형태로 변경 가능하도록 함.
> 🔧 config : 데이터베이스 접속 정보 변경에 따른 url parse 옵션 추가

- server/jest/challenge.spec.js
- server/jest/mypage.spec.js
> test code 수정

- server/controller/proofshot.js
- server/jest/proofshot.spec.js
- server/modules/calcProperty.js
1. 3일차에 보상 랜덤으로 주도록 함수추가
2. 3의 배수 번째 인증할 때 인증값 검사하는 테스트 코드 수정
> 챌린지 인증 3일차 보상 관련 함수 추가 및 테스트 코드 수정

- server/modules/calcProperty.js
pastDays의 항목이 소수점으로 나오던 것을 수정함.
> 🐛 챌린지 조회에서 경과날짜가 소수점으로 나오는 현상 수정

- server/controller/proofshot.js
- server/controller/user.js
- server/jest/proofshot.spec.js
- server/models/user.js
- server/routes/user.js
> Ranking API 추가

- server/controller/user.js
Ranking API proofCnt 가 같은 경우 공동순위로 처리
> Ranking API 공동순위 처리

- server/modules/swagger.js
Swagger에 Nginx 서버 주소 추가해주었습니다.
> Swagger에 Nginx 서버 주소 추가

- server/passport/index.js
소셜로그인에 필요한 callback url 숨김 처리 진행.
> 🔒️ 카카오톡 소셜 로그인 callback url 변경

- server/controller/user.js
> Ranking API 리턴값 수정

- server/controller/user.js
`item_order` = `['background', 'color', 'clothes', 'acc', 'emotion']` 의 순서로 전달하려 변경.
> 🐛 전체 랭킹 조회 시, 사용자의 아이템 정렬 순서를 일정한 순서로 보내도록 변경

- server/controller/mypage.js
- server/routes/mypage.js
마이페이지에서 사용될 나의 총 인증횟수, 챌린지 참가 수 전달하는 API 추가
> ✨ 나의 총 인증횟수, 챌린지 참가 수 조회 API 추가

- server/modules/calcProperty.js
status 값이 여전히 당일 참가가 안되는 현상 있어서 수정.
> 🐛 챌린지 정책 관련 수정 중, 누락된 status 값 변경 수정

- server/controller/challenge.js
- server/controller/mypage.js
- server/jest/challenge.spec.js
- server/modules/multer.js
> Image resizing

- server/controller/challenge.js
- server/controller/mypage.js
- server/modules/calcProperty.js
- server/routes/challenge.js
<주의>
1. 챌린지 수정 버튼은 자기가 쓴 글이고 startAt이 내일 날짜 이후인 글에만 나타남
2. 챌린지 수정할 때 startAt은 내일 날짜 이후로만 바꿀 수 있음.
> Challenge 수정 API 작성

- server/controller/auth.js
- server/controller/character.js
- server/controller/mypage.js
- server/controller/proofshot.js
- server/jest/calcProperty.spec.js
- server/middlewares/auth-middleware.js
- server/modules/calcProperty.js
- server/passport/index.js
calcUploadStatus 에서 오늘 날짜를 포함해서 30일이므로 if (dateDiff >= 30) { i.status = 2; //완료} 로 수정했습니다.
기존 코드 calcRound에서 Round 가 10보다 큰 경우 10을 반환하도록 변경했습니다.
> calcUploadStatus 수정

- server/controller/user.js
랭킹 데이터 표시 기준 수정 ( 같은 랭킹의 유저들 뒤에 나오는 유저 랭킹 값에 대한 기준 1 2 2 3 4 => 1 2 2 4 5 )
> 게스트 유저에 대한 랭킹 페이지 정보 삽입

- .gitignore
- server/controller/user.js
Ranking api populate 제거 통한 성능 개선
굳이 item을 찾기 위해 db에 여러번 접근할 필요가 없음.
최초 한번 item리스트를 불러온 뒤, item 배열에서 해당하는 아이템을 찾아서 넣어주는 형태로 개선시킴
> Ranking api 성능 개선

- server/controller/user.js
> 랭킹 api 성능 개선

- server/controller/character.js
- server/controller/user.js
- server/jest/character.spec.js
- server/models/user.js
find character 제거, user에 snap equippedItems 스냅샷 추가
> 랭킹 api 2차 성능 개선 

- server/controller/character.js
- server/controller/user.js
유저 회원가입시 equippedItem 같이 수정하도록 변경
캐릭터 아이템 구입시 equippedItem 같이 수정하도록 변경
> 랭킹 api 관련 버그 수정

- server/server.js
> chore: slack app notification test

- server/server.js
> slack alarm test
